config/routes.rb
Rails.application.routes.draw do
  resources :rides 
  resources :drivers 
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_many :rides
    has_many :users, through: :rides 
end

app/models/ride.rb
class Ride < ApplicationRecord
    belongs_to :driver
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rides
    has_many :drivers, through: :rides 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
 
    before_action :get_driver, only: [:show ,:edit , :update ,:destroy ]

    def index
        @drivers = Driver.all
    end 

   
    def new
        @driver = Driver.new() 
    end 

    def create
       @driver = Driver.create(driver_strong_params) 
       redirect_to drivers_path
    end 

    def update
        @driver.update(driver_strong_params)
        redirect_to driver_path(@driver)
    end 

    def destroy
        @driver.destroy
        redirect_to drivers_path
    end 

    private

    def get_driver
        @driver = Driver.find(params[:id])
    end 

    def driver_strong_params
        params.require(:driver).permit(:name,:car,:rating)
    end 


end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index
    @users = User.all
   end 

   def show
   end 
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drivers/_driver_form.html.erb
<%= form_for @driver do |d|%>
<%= d.label :name%>
<%= d.text_field :name%><br>
<%= d.label :car%>
<%= d.text_field :car%><br>
<%= d.label :rating %>
<%= d.number_field :rating%><br>
<%= d.submit %>
<% end %> 

app/views/drivers/edit.html.erb
<h1> Edit Details for <% @driver.name %> </h1>
<%= render partial: "driver_form" %>

app/views/drivers/index.html.erb
<h1> Welcome to My Uber App </h1>
<h3> List of Drivers </h3>

<ul>
<% @drivers.each do |drive| %>
<li>
<%= link_to drive.name , driver_path(drive)%>
<% end %>
</li>
</ul>

<%= link_to "New Driver" ,  new_driver_path %>

app/views/drivers/new.html.erb
<h1> Create a New Driver </h2>

<%= render partial: "driver_form"%>

app/views/drivers/show.html.erb
<h2>  Driver <%=@driver.name %> </h2>

Car :    <%= @driver.car %><br>
Rating:  <%= @driver.rating %><br><br>


<%= link_to "Edit Driver" , edit_driver_path(@driver) %><br><br>
<%= button_to "Delete Driver" , driver_path(@driver) , :method => :delete , data: {:confirm => "are you sure"} %><br>
<%= link_to "Home Page" , drivers_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> Current Users   </h1> 

<% @users.each do |user| %>
<h2><%= user.name %></h2>
<% end %> 